environment:
  msvs_toolset: 14
  BOOST_VERSION: 59
  FASTBUILD: 1
  matrix:
    - platform: x64
      configuration: Release

os: Visual Studio 2015

#shallow_clone: true
# limit clone to latest 5 commits
clone_depth: 5

install:
  - scripts\build-appveyor.bat

artifacts:
  - path: mapnik-gyp\msbuild-summary.txt
    name: msbuild-summary.txt
  - path: mapnik-gyp\msbuild-errors.txt
    name: msbuild-errors.txt
  - path: mapnik-gyp\msbuild-warnings.txt
    name: msbuild-warnings.txt

build: off
test: off
deploy: off
